name: ci

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Install apt-get packages
      run: |
        sudo ACCEPT_EULA=Y apt-get update
        sudo ACCEPT_EULA=Y apt-get upgrade
        sudo apt-get install wget git curl software-properties-common build-essential

    - name: Install and run MySQL
      run: |
        sudo apt-get update
        sudo apt-get -y install mysql-server libmysqlclient-dev curl
        sudo service mysql start
        mysql -e "SET GLOBAL max_allowed_packet = 36700160;" -uroot -proot
        mysql -e "SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = WARN;" -uroot -proot
        mysql -e "SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = ON;" -uroot -proot
        mysql -e "SET @@GLOBAL.GTID_MODE = OFF_PERMISSIVE;" -uroot -proot
        mysql -e "SET @@GLOBAL.GTID_MODE = ON_PERMISSIVE;" -uroot -proot
        mysql -e "SET @@GLOBAL.GTID_MODE = ON;" -uroot -proot
        mysql -e "PURGE BINARY LOGS BEFORE now();" -uroot -proot
    
    - name: Install and run Redpanda
      run: |
        curl -1sLf 'https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.deb.sh' | sudo -E bash
        sudo apt install redpanda -y
        sudo systemctl start redpanda
    
    - name: Install Rust target for wasm
      run: |
        rustup target add wasm32-wasi

    - name: Install WasmEdge
      run: |
        VERSION=0.11.2
        curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | sudo bash -s -- --version=$VERSION -p /usr/local

    - name: Run the webhook ETL service on MySQL
      run: |
        cd examples/order
        cargo clean
        cargo build --target wasm32-wasi --release
        wasmedgec target/wasm32-wasi/release/order.wasm order.wasm
        nohup wasmedge --env "DATABASE_URL=mysql://root:root@127.0.0.1:3306/mysql" order.wasm &
        echo $! > wasmedge.pid
        sleep 15
        
    - name: Test the webhook ETL service
      run: |
        cd examples/order
        ls -al
        echo $'\nSend an order'
        curl http://localhost:3344/ -X POST -d @order.json
        echo $'\nQuery DB'
        mysql -u root -proot mysql -e "select * from orders"
        echo $'\Delete DB'
        mysql -u root -proot mysql -e "drop table orders"
        echo $'\nDone!'
        cat nohup.out
        kill -9 `cat wasmedge.pid`
        rm wasmedge.pid

    - name: Run the Redpanda ETL service on MySQL
      run: |
        cd examples/kafka
        cargo clean
        cargo build --target wasm32-wasi --release
        wasmedgec target/wasm32-wasi/release/kafka.wasm kafka.wasm
        nohup wasmedge --env "DATABASE_URL=mysql://root:root@127.0.0.1:3306/mysql" --env "KAFKA_URL=kafka://127.0.0.1:9092/order" kafka.wasm &
        echo $! > wasmedge.pid
        sleep 15
        
    - name: Test the Redpanda ETL service
      run: |
        cd examples/kafka
        ls -al
        # echo $'\nCreate a queue topic'
        # rpk topic create order
        echo $'\nSend an order'
        cat order.json | rpk topic produce order
        sleep 5
        echo $'\nQuery DB'
        mysql -u root -proot mysql -e "select * from orders"
        echo $'\Delete DB'
        mysql -u root -proot mysql -e "drop table orders"
        echo $'\nDone!'
        cat nohup.out
        kill -9 `cat wasmedge.pid`
        rm wasmedge.pid

    
